---
apiVersion: v1
kind: Namespace
metadata:
  name: staging2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: staging2
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: yahcontainers/myapi
        ports:
        - name: http
          containerPort: 3000
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 300m
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: staging2
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 3000